### Get tasks 
GET https://todo-backend-47er.onrender.com/

### Add new task
POST https://todo-backend-47er.onrender.com/new HTTP/1.1
Content-Type: application/json
 
{
  "description": "Test from REST Client"
}

### Delete task
DELETE https://todo-backend-47er.onrender.com/delete/11 HTTP/1.1